name: BanItem
author: LDX
version: 2.3.3
api: 4.0.0
main: LDX\BanItem\Main
load: POSTWORLD
website: https://github.com/LDX-MCPE/BanItem
commands:
  banitem:
    description: "BanItem main command."
    permission: banitem.command.banitem
    usage: "/banitem <ban/unban/list/report> [ID[:Damage]]"
permissions:
  banitem:
    default: op
    description: "Allows access to all BanItem features."
  banitem.bypass:
    default: op
    description: "Allows access to using banned items."
  banitem.command:
    default: op
    description: "Allows access to all BanItem commands."
  banitem.command.banitem:
    default: op
    description: "Allows access to the item command."